forgot about variable scope...

diff --git a/mkpkg_32to64 b/mkpkg_32to64
--- a/mkpkg_32to64
+++ b/mkpkg_32to64
@@ -42,8 +42,8 @@ make_compat32() {
 	cp ${orig_dir}/install/data.xml ${dest_dir}/install/data.xml
 
 	# Copy libs
-	local copied_once=0
 	( cd ${orig_dir}
+		copied_once=0
 		for i in $(find . -name '*.so') $(find . -name '*.so.*') ; do
 			dirname=$(dirname $i)
 			check_dir_whitelist $dirname || continue
@@ -53,11 +53,11 @@ make_compat32() {
 			cp -a $i ${dest_dir}/$i
 			copied_once=1
 		done
+		if [ "$copied_once" == "0" ] ; then
+			echo "ERROR: package has no libs, output will be empty. Aborting build"
+			exit 1
+		fi
 	)
-	if [ "$copied_once" = "0" ] ; then
-		echo "ERROR: package has no libs, output will be empty. Aborting build"
-		exit 1
-	fi
 
 	# Copy ABUILD
 	pkginfo="$(mkpkg_xml_parser $dest_dir/install/data.xml -p)"
